jonashaag/klaus

CHANGELOG.rst, bin/klaus
Add command-line argument --browser (shortened to -b) which will
auto-launch a web-browser pointing to the Klaus server via the Python
webbrowser module.
Note that we do things in the wrong order in that we launch the browser
and *then* start the server. In the absence of a cleaner way of getting
a function to run after server setup this approach actually works in
practice. If this doesn't Just Work for someone we can think again about
more complex options.
=> add option to auto-launch browser on server

bin/klaus
As noted in #108, the ``--browser`` option is currently broken if no
argument is supplied. Split the argument into two: a flag
(``--browser``) indicating if a browser is to be opened and an option
(``--with-browser``) which may optionally be used to specify which
browser is to be used.
Fixes #108.
=> split browser option into flag and option

klaus/contrib/wsgi_autoreload.py
Fix errant .split() calls that causes a TypeError when trying to use the wsgi_autoreload component
Fixed #116
=> Fix errant .split() calls that causes a TypeError

klaus/tarutils.py
tarutils.py breaks under python 2.6. This workaround fixes it.
=> Tarutils Python 2.6 compatibility

README.rst, klaus/contrib/wsgi_autoreload.py
hi,
it looks like `make_autoreloading_app` doesnt really work right now - it accepts `KLAUS_REPOS` as a param (which is supposed to be a list of directories), but when it spawns a thread to monitor changes later, it expects just a single directory there.
So I've added another env variable `KLAUS_REPOS_ROOT`, which can be used for specifying a parent directory for repositories in it, instead of defining a list of repositories explicitly.
This change is backward compatible, as it fallbacks to `KLAUS_REPOS` in case `KLAUS_REPOS_ROOT` is not defined.
=> allow to specify repositories root

klaus/contrib/wsgi_autoreload.py
this assignment is wrong - it's `old_contents` which needs to be reassigned, not `new_contents`
=> fix autoreload condition

klaus/__init__.py, klaus/utils.py
@jelmer Please try this; note that `X-Scheme` has been changed to the de facto standard `X-Forwarded-Proto`. (Although there seems to be RFC 7239 with the `Forwarded` header, see mitsuhiko/werkzeug#800)
=> Add ProxyFix, deprecate SubUri (incorrect behavior)

klaus/utils.py
This should work as expected. The only difference is that if SCRIPT_NAME is not set, it will stay unset when it would have been set to `""` previously.
=> Do not change SCRIPT_NAME if HTTP_X_SCRIPT_NAME isn't set, fixes #155

klaus/views.py
I noticed while testing python-ctags that if a non-ASCII character is present in the file path, this would not work on Windows. I don't know how well python-ctags or klaus work on other platforms but this should be future-proof.
=> ctags: improve portability

klaus/templates/base.html
fd0ee00949c9aad3140d5d850864ae43fb9ea40a deleted the /history page.
=> Link to index page rather than history page.

klaus/repo.py, klaus/templates/history.inc.html
This addresses #122 when the smart server is disabled.
At the moment this displays the URL in addition to the smart server URL if repo.cloneurl is set.
=> Support gitweb .git/cloneurl file and 'gitweb.url' settings.

klaus/markup.py
This extension is used by ikiwiki.
=> Add ".mdwn" as a markdown extension.

klaus/__init__.py, klaus/templates/base.html, klaus/utils.py, klaus/views.py
This fixes two bugs:
* #36 is fixed by forward-porting closed PR #103 
* The drop-down list of branches doesn't work on the index page because query string parameters aren't parsed; this adds parsing so that the rev can be specified in the query string.
=> Handle refs that contain a / properly

.travis.yml, setup.py
pygments also no longer supports 2.6.
This should fix the build on travis.
=> Drop support for Python2.6. Fixes #184

klaus/repo.py
Tags do not have commit times, but they do appear in the list of
refs. This makes klaus use the latest ref that has a commit_time when
finding the last updated time for a repo.
The easiest way to replicate this is with a repo that contains no commits, only a tag.
=> Fix bug when the latest ref on a repo is a tag

klaus/__init__.py, klaus/repo.py, klaus/templates/submodule.html, klaus/templates/tree.inc.html, klaus/views.py
Currently, this just shows some basic information about the submodule -
i.e. where the repository can be cloned from, and the revision that is
referenced.
Partially addresses #1. In the future, this page could redirect to the
actual submodule repository history page.
=> Link submodules to an info page, rather than showing a 404.

setup.py
HI, I guess this isn't needed since https://github.com/jonashaag/klaus/commit/7cc4c13a95ac9ea023e1ab2a383bfb38098bb0e1
=> Drop argparse requirement (included in Python 2.7+)

tests/repos/scripts/dont-render, tests/repos/scripts/no-newline-at-end-of-file, tests/repos/scripts/test_repo
removed the `--no-gpg-sign` from PR #141 and overrites the HOME variable to
force git using an empty config.
see changes in:
* tests/repos/scripts/dont-render
* tests/repos/scripts/no-newline-at-end-of-file
* tests/repos/scripts/test_repo
I'll hope it helps!
cheers
=> Fixes #144 - Blank Git user config for tests

klaus/views.py
May I propose this one-line change?
The Principled Justification: [elsewhere in the source code](https://github.com/jonashaag/klaus/blob/876ba7536a06c9040e0057ba4b29e0d3d4fb51d2/klaus/markup.py#L33), files with these extensions are treated as Markdown, so they should here too, for consistency.
The Pragmatic Argument: GitHub recognizes these files as READMEs written in Markdown, so klaus should too.
=> Recognize more Markdown file extensions for READMEs.

klaus/utils.py, tests/test_utils.py
Properly keep track of exception so it can be reraised in force_unicode.
Without this, the last line of force_unicode() fails because of an undefined
variable "exc" on Python 3.
=> Properly keep track of exception so it can be reraised in force_unicode.

klaus/static/klaus.css, klaus/views.py
If readme files contain markup, they weren't displayed correctly in the
index view (no padding, no grey box).
The fix contains two changes:
- Use `force_unicode` on the readme's filename
- use the CSS properties for both blobview and non-blobview
=> fix display of code blocks in index view

klaus/utils.py, tests/test_utils.py
Try a bit harder to come up with sensible names for tarballs and prefixes in tarballs.
For revisions without a tag associated, keep the current name, i.e.:
SHA => klaus@SHA
For tags, cope with common syntaxes for tags:
0.1 => klaus-0.1
v0.1 => klaus-0.1
klaus-0.1 => klaus-0.1
=> Try a bit harder to come up with sensible names for tarballs and prefixes in tarballs.

klaus/repo.py
When determining last update to a repository, ignore refs that point at missing objects.
This shouldn't normally happen, but when it does, it should not make klaus
crash altogether.
Both C Git and Dulwich will print these tags but print warnings about them.
=> When determining last update to a repository, ignore refs that point at missing objects.

.travis.yml
Fix travis tests for python 3.7.
3.7 is not available for trusty.
=> Fix travis tests for python 3.7.

klaus/repo.py, setup.py, tests/test_manpage.py
Use an older version of Dulwich on Python 2.x.
Fixes #252
=> Use an older version of Dulwich on Python 2

Dockerfile
Package 'pip3' is not found during the docker image build.
Fixed by 'py3-pip'.
=> fix 'pip3' missing

.travis.yml
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.
=> added power support arch on yml file.

klaus/views.py
Check that README is actually a blob, not a tree.
I did find one upstream package that has a directory called README :)
=> Check that README is actually a blob, not a tree

Dockerfile
This allows building forks etc by specifying e.g. a git+http:// URL.
If the argument is not specified, KLAUS_VERSION behaves as before.
=> Add KLAUS_URL build argument to Dockerfile

klaus/repo.py, runtests.sh, tests/repos/scripts/test_repo, tests/test_blame.py
Support viewing blame of empty files.
Without this, klaus tries to access repo[b''] which leads to a KeyError.
=> Support viewing blame of empty files

klaus/utils.py, tests/test_utils.py
Fall back to just converting unknown bytestings using latin1, replacing invalid characters.
This at least allows rendering pages rather than throwing 500s.
=> Fall back to just converting unknown bytestings using latin1, replacing invalid characters

klaus/repo.py
diff: Cope with missing objects.
This should fix exceptions with undefined newblob, when there's a submodule that's the first path in the tree.
=> diff: Cope with missing objects

klaus/views.py
Fix 500 error when accessing history of blob objects.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/lib/python3/dist-packages/flask/views.py", line 84, in view
return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
File "/home/jelmer/src/klaus/klaus/views.py", line …
=> Fix 500 error when accessing history of blob objects

klaus/repo.py
Add 'main' to the list of default branch names to try.
This is now commonly used by many projects instead of "master".
=> Add 'main' to the list of default branch names to try

klaus/utils.py
Replace invalid characters even when chardet has found an encoding
In some cases, it seems to find an encoding that's not valid for the entire string.
=> Replace invalid characters even when chardet has found an encoding

klaus/repo.py
@benaryorg please try this, closes #309
=> Fix slow repo_list with many refs

klaus/repo.py, klaus/views.py
=> Repo page: if no default branch is found, use HEAD

klaus/utils.py
An example of this is e.g. EUC-TW
=> Handle chardet returning encodings unknown by Python

Dockerfile
I tried to build the docker container, it refused to install the pip packages throwing `error: externally-managed-environment`
I think as long this is used inside a docker container it is okay to use the `--break-system-packages` option of pip. 
Otherwise according to a note while trying to install with pip a venv is recommended.
=> Fix docker build error of externally-managed-environment

klaus/contrib/app_args.py, setup.py
remove references to distutils
- `app_args.py`: add polyfill
- `setup.py`: remove code that hasn't been necessary since 51094d7
=> python 3.12 support
